version: "3.1"
services:
  app:
    build: ./docker/php
    container_name: aartur_app
    volumes:
      - ./:/var/www
  webserver:
    image: nginx
    container_name: artur-webserver-1
    working_dir: /var/www
    volumes:
      - ./public/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build: docker/php
    container_name: artur-php-fpm-1
    working_dir: /www
    volumes:
      - ./public/:/var/www