version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - 2222:80
    volumes:
      - ./nginx:/var/www
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./public:/var/www